# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Animation' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Animation

  target 'AnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimationUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry', '~> 1.0.1'
pod 'YYModel', '~> 1.0.4'
pod 'YYCache', '~> 1.0.3'
pod 'YYImage', '~> 1.0.3'
pod 'YYWebImage', '~> 1.0.4'
pod 'YYText', '~> 1.0.5'
pod 'YYKeyboardManager', '~> 1.0.1'
pod 'YYDispatchQueuePool', '~> 1.0'
pod 'YYCategories', '~> 1.0.3'
pod 'YYAsyncLayer', '~> 1.0'
end
