# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Animation' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Animation

  target 'AnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimationUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry', '~> 1.0.1'
end
